########################################################################
# Test --sdi-to-sql: reads SDI directly from .ibd files via raw page
# I/O and generates CREATE TABLE SQL without --prepare or --export.
#
# Modes tested:
#   1. --sdi-to-sql --ibd-file=<path>   (single file)
#   2. --sdi-to-sql --database-dir=<path> (directory of .ibd files)
#
# Covers: non-partitioned tables, partitioned tables, general
#         tablespace, and roundtrip verification.
#
# Uses the live MySQL data directory for consistent .ibd files.
########################################################################

. inc/common.sh

start_server

DATADIR=$(mysql -e "SELECT @@datadir" -N -B)

# ----- Create test tables -----

# t1: simple table
mysql -e "CREATE TABLE t1 (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100),
  PRIMARY KEY (id)
) ENGINE=InnoDB" test

# t2: table with indexes and comments
mysql -e "CREATE TABLE t2 (
  a INT NOT NULL,
  b VARCHAR(255) DEFAULT 'hello',
  c DECIMAL(10,2),
  PRIMARY KEY (a),
  KEY idx_b (b(50))
) ENGINE=InnoDB COMMENT='test table t2'" test

# t3: partitioned table (RANGE)
mysql -e "CREATE TABLE t3 (
  id INT NOT NULL,
  val INT,
  PRIMARY KEY (id)
) ENGINE=InnoDB
PARTITION BY RANGE (id) (
  PARTITION p0 VALUES LESS THAN (100),
  PARTITION p1 VALUES LESS THAN (200),
  PARTITION p2 VALUES LESS THAN MAXVALUE
)" test

# t4: general tablespace with two tables
mysql -e "CREATE TABLESPACE ts1 ADD DATAFILE 'ts1.ibd' ENGINE=InnoDB"
mysql -e "CREATE TABLE t4a (x INT PRIMARY KEY) ENGINE=InnoDB TABLESPACE ts1" test
mysql -e "CREATE TABLE t4b (y INT PRIMARY KEY, z VARCHAR(50)) ENGINE=InnoDB TABLESPACE ts1" test

# Flush to ensure SDI is written to disk
mysql -e "FLUSH TABLES t1, t2 FOR EXPORT" test
sleep 1

# Copy .ibd files while tables are export-locked
cp ${DATADIR}/test/t1.ibd $topdir/t1.ibd
cp ${DATADIR}/test/t2.ibd $topdir/t2.ibd

mysql -e "UNLOCK TABLES" test

# =======================================================================
# Test 1: --sdi-to-sql --ibd-file (single non-partitioned table)
# =======================================================================
vlog "=== Test 1: --ibd-file with t1.ibd ==="

rm -f $topdir/t1.sql

xtrabackup --sdi-to-sql --ibd-file=$topdir/t1.ibd \
    > $topdir/stdout_t1.sql 2>$topdir/stderr_t1.log

# Verify .sql file was written alongside the .ibd
if [ ! -f "$topdir/t1.sql" ]; then
    vlog "ERROR: t1.sql was not generated"
    cat $topdir/stderr_t1.log >&2
    exit -1
fi

# Verify stdout contains CREATE TABLE
if ! grep -q "CREATE TABLE" $topdir/stdout_t1.sql; then
    vlog "ERROR: stdout does not contain CREATE TABLE"
    cat $topdir/stdout_t1.sql >&2
    exit -1
fi

vlog "Generated t1.sql contents:"
cat $topdir/t1.sql >&2
vlog "Test 1 passed: --ibd-file generated t1.sql"

# =======================================================================
# Test 2: --sdi-to-sql --database-dir (all tables in directory)
# =======================================================================
vlog "=== Test 2: --database-dir ==="

# Flush and copy partition files too
mysql -e "FLUSH TABLES t3, t4a, t4b FOR EXPORT" test
sleep 1

mkdir -p $topdir/testdb
cp ${DATADIR}/test/*.ibd $topdir/testdb/ 2>/dev/null || true

mysql -e "UNLOCK TABLES" test

xtrabackup --sdi-to-sql --database-dir=$topdir/testdb/ \
    > $topdir/stdout_dir.sql 2>$topdir/stderr_dir.log

# Verify .sql files for non-partitioned tables
for tbl in t1 t2; do
    if [ ! -f "$topdir/testdb/${tbl}.sql" ]; then
        vlog "ERROR: ${tbl}.sql was not generated by --database-dir"
        cat $topdir/stderr_dir.log >&2
        exit -1
    fi
done

vlog "Test 2 passed: --database-dir generated .sql files"

# =======================================================================
# Test 3: Partition table (SDI only in first partition)
# =======================================================================
vlog "=== Test 3: partitioned table t3 ==="

if [ ! -f "$topdir/testdb/t3.sql" ]; then
    vlog "ERROR: t3.sql was not generated for partitioned table"
    cat $topdir/stderr_dir.log >&2
    exit -1
fi

if ! grep -q "CREATE TABLE" $topdir/testdb/t3.sql; then
    vlog "ERROR: t3.sql does not contain CREATE TABLE"
    exit -1
fi

if ! grep -q "PARTITION" $topdir/testdb/t3.sql; then
    vlog "ERROR: t3.sql does not contain PARTITION definition"
    exit -1
fi

vlog "Generated t3.sql contents:"
cat $topdir/testdb/t3.sql >&2
vlog "Test 3 passed: partitioned table t3.sql generated correctly"

# =======================================================================
# Test 4: General tablespace (single .ibd, multiple CREATE TABLEs)
# =======================================================================
vlog "=== Test 4: general tablespace ts1 ==="

rm -f $topdir/ts1.sql
mysql -e "FLUSH TABLES t4a, t4b FOR EXPORT" test
sleep 1
cp ${DATADIR}/ts1.ibd $topdir/ts1.ibd
mysql -e "UNLOCK TABLES" test

xtrabackup --sdi-to-sql --ibd-file=$topdir/ts1.ibd \
    > $topdir/stdout_ts1.sql 2>$topdir/stderr_ts1.log

if [ ! -f "$topdir/ts1.sql" ]; then
    vlog "ERROR: ts1.sql was not generated for general tablespace"
    cat $topdir/stderr_ts1.log >&2
    exit -1
fi

vlog "Generated ts1.sql contents:"
cat $topdir/ts1.sql >&2

if ! grep -q "CREATE TABLESPACE" $topdir/ts1.sql; then
    vlog "ERROR: ts1.sql does not contain CREATE TABLESPACE"
    exit -1
fi

# Should contain both t4a and t4b
t4_count=$(grep -c "CREATE TABLE" $topdir/ts1.sql || true)
if [ "$t4_count" -lt 2 ]; then
    vlog "ERROR: ts1.sql should contain at least 2 CREATE TABLE statements, found $t4_count"
    exit -1
fi

vlog "Test 4 passed: general tablespace ts1.sql has CREATE TABLESPACE + multiple CREATE TABLE"

# =======================================================================
# Test 5: Roundtrip verification for t1 and t2
# =======================================================================
vlog "=== Test 5: roundtrip verification ==="

for tbl in t1 t2; do
    ${MYSQLDUMP} ${MYSQL_ARGS} --no-data --skip-comments --skip-dump-date \
        test "$tbl" > $topdir/original_${tbl}.sql

    mysql -e "SET foreign_key_checks=0; DROP TABLE \`$tbl\`" test
    (echo "SET foreign_key_checks=0;"; cat $topdir/testdb/${tbl}.sql) | mysql test

    ${MYSQLDUMP} ${MYSQL_ARGS} --no-data --skip-comments --skip-dump-date \
        test "$tbl" > $topdir/recreated_${tbl}.sql

    run_cmd diff -u $topdir/original_${tbl}.sql $topdir/recreated_${tbl}.sql
    vlog "Roundtrip passed for $tbl"
done

vlog "Test 5 passed: roundtrip verification successful"

# =======================================================================
# Cleanup
# =======================================================================
mysql -e "DROP TABLE IF EXISTS t4a, t4b" test
mysql -e "DROP TABLESPACE ts1" 2>/dev/null || true
mysql -e "DROP TABLE IF EXISTS t3, t2, t1" test

vlog "All sdi_to_sql tests passed"
