/******************************************************
Copyright (c) 2026 Percona LLC and/or its affiliates.

backup_metadata.json writer.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 2 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

*******************************************************/

#include "xb_manifest.h"

#include <my_rapidjson_size_t.h>
#include <rapidjson/document.h>
#include <rapidjson/prettywriter.h>
#include <rapidjson/stringbuffer.h>

#include <cctype>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <map>
#include <sstream>
#include <string>

#include "common.h"
#include "msg.h"

namespace {

/* Cache for the verbatim text of each legacy info file as it is
generated by the backup process.  Keyed by file basename
(e.g. "xtrabackup_info").  Filled in by xb_manifest::set_legacy_text;
read back at backup_finish to build the manifest. */
std::map<std::string, std::string> g_legacy_text;

/* Parse a "key = value\n" block (the format used by xtrabackup_info,
xtrabackup_checkpoints) into a JSON object.  Numeric-looking values
are emitted as integers; everything else as strings.  Empty values
become empty strings. */
void parse_key_value_block(const std::string &text, rapidjson::Value &out,
                           rapidjson::Document::AllocatorType &alloc) {
  out.SetObject();
  std::istringstream is(text);
  std::string line;
  while (std::getline(is, line)) {
    /* Trim trailing whitespace (including \r on cross-platform files). */
    while (!line.empty() &&
           (line.back() == ' ' || line.back() == '\t' || line.back() == '\r')) {
      line.pop_back();
    }
    if (line.empty()) continue;
    const auto eq = line.find('=');
    if (eq == std::string::npos) continue;
    std::string key = line.substr(0, eq);
    std::string val = line.substr(eq + 1);
    /* Trim surrounding whitespace from key and value. */
    auto trim = [](std::string &s) {
      while (!s.empty() && (s.front() == ' ' || s.front() == '\t'))
        s.erase(s.begin());
      while (!s.empty() && (s.back() == ' ' || s.back() == '\t')) s.pop_back();
    };
    trim(key);
    trim(val);
    if (key.empty()) continue;

    /* Decide numeric vs string: only emit as integer when the value
    is a pure decimal that fits in int64_t.  Otherwise keep as
    string (preserves binlog filenames, GTIDs, uuids, etc.). */
    bool numeric =
        !val.empty() && std::all_of(val.begin(), val.end(),
                                     [](char c) { return std::isdigit(c); });
    rapidjson::Value k(key.c_str(), key.size(), alloc);
    if (numeric) {
      try {
        const long long n = std::stoll(val);
        out.AddMember(k, rapidjson::Value(static_cast<int64_t>(n)), alloc);
      } catch (...) {
        rapidjson::Value v(val.c_str(), val.size(), alloc);
        out.AddMember(k, v, alloc);
      }
    } else {
      rapidjson::Value v(val.c_str(), val.size(), alloc);
      out.AddMember(k, v, alloc);
    }
  }
}

/* Parse xtrabackup_binlog_info -- a single line of TSV:
   "<filename>\t<position>[\t<gtid_executed>]\n"
into {"filename": ..., "position": ..., "gtid_executed": ...}.  If the
text is empty, leaves out a null sentinel. */
void parse_binlog_info(const std::string &text, rapidjson::Value &out,
                       rapidjson::Document::AllocatorType &alloc) {
  out.SetObject();
  /* Trim trailing newline / whitespace. */
  std::string s = text;
  while (!s.empty() && (s.back() == '\n' || s.back() == '\r' ||
                        s.back() == ' ' || s.back() == '\t')) {
    s.pop_back();
  }
  if (s.empty()) return;
  const auto tab1 = s.find('\t');
  if (tab1 == std::string::npos) return;
  const std::string filename = s.substr(0, tab1);
  std::string rest = s.substr(tab1 + 1);
  const auto tab2 = rest.find('\t');
  std::string position_str;
  std::string gtid;
  if (tab2 == std::string::npos) {
    position_str = rest;
  } else {
    position_str = rest.substr(0, tab2);
    gtid = rest.substr(tab2 + 1);
  }

  rapidjson::Value v_filename(filename.c_str(), filename.size(), alloc);
  out.AddMember("filename", v_filename, alloc);
  try {
    const long long pos = std::stoll(position_str);
    out.AddMember("position", rapidjson::Value(static_cast<int64_t>(pos)),
                  alloc);
  } catch (...) {
    rapidjson::Value v_pos(position_str.c_str(), position_str.size(), alloc);
    out.AddMember("position", v_pos, alloc);
  }
  rapidjson::Value v_gtid(gtid.c_str(), gtid.size(), alloc);
  out.AddMember("gtid_executed", v_gtid, alloc);
}

}  // namespace

namespace xb_manifest {

void set_legacy_text(const char *name, const std::string &text) {
  g_legacy_text[name] = text;
}

const std::string &get_legacy_text(const char *name) {
  static const std::string empty;
  auto it = g_legacy_text.find(name);
  return it == g_legacy_text.end() ? empty : it->second;
}

std::string build_json() {
  rapidjson::Document doc;
  doc.SetObject();
  auto &alloc = doc.GetAllocator();

  /* Schema version. */
  doc.AddMember("manifest_version", rapidjson::Value(1), alloc);

  /* xtrabackup_info -- structured. */
  {
    rapidjson::Value v;
    const auto &text = get_legacy_text("xtrabackup_info");
    if (text.empty()) {
      v.SetNull();
    } else {
      parse_key_value_block(text, v, alloc);
    }
    doc.AddMember("xtrabackup_info", v, alloc);
  }

  /* xtrabackup_binlog_info -- structured (filename/position/gtid). */
  {
    rapidjson::Value v;
    const auto &text = get_legacy_text("xtrabackup_binlog_info");
    if (text.empty()) {
      v.SetNull();
    } else {
      parse_binlog_info(text, v, alloc);
    }
    doc.AddMember("xtrabackup_binlog_info", v, alloc);
  }

  /* xtrabackup_checkpoints -- structured. */
  {
    rapidjson::Value v;
    const auto &text = get_legacy_text("xtrabackup_checkpoints");
    if (text.empty()) {
      v.SetNull();
    } else {
      parse_key_value_block(text, v, alloc);
    }
    doc.AddMember("xtrabackup_checkpoints", v, alloc);
  }

  /* xtrabackup_galera_info / xtrabackup_replica_info /
  xtrabackup_slave_info -- raw text for v1; embedded as JSON strings
  so consumers can read them out without re-fetching from disk (in
  stream/cloud modes the legacy files do not live locally).  Future
  versions may parse these into structured form if a consumer needs
  it. */
  auto embed_raw = [&](const char *manifest_key, const char *legacy_name) {
    rapidjson::Value v;
    const auto &text = get_legacy_text(legacy_name);
    if (text.empty()) {
      v.SetNull();
    } else {
      v.SetString(text.c_str(), text.size(), alloc);
    }
    doc.AddMember(rapidjson::StringRef(manifest_key), v, alloc);
  };
  embed_raw("xtrabackup_galera_info", "xtrabackup_galera_info");
  embed_raw("xtrabackup_replica_info", "xtrabackup_replica_info");
  embed_raw("xtrabackup_slave_info", "xtrabackup_slave_info");

  rapidjson::StringBuffer buf;
  rapidjson::PrettyWriter<rapidjson::StringBuffer> writer(buf);
  writer.SetIndent(' ', 2);
  doc.Accept(writer);
  return std::string(buf.GetString(), buf.GetSize());
}

bool publish(ds_ctxt_t *ds_root, const std::string &json_text) {
  ds_file_t *file =
      ds_open_single_object(ds_root, XB_BACKUP_METADATA_JSON, nullptr);
  if (file == nullptr) {
    msg("xb_manifest::publish: ds_open_single_object failed for %s\n",
        XB_BACKUP_METADATA_JSON);
    return false;
  }
  if (ds_write(file, json_text.data(), json_text.size()) != 0) {
    msg("xb_manifest::publish: ds_write failed for %s\n",
        XB_BACKUP_METADATA_JSON);
    ds_close(file);
    return false;
  }
  if (ds_close(file) != 0) {
    msg("xb_manifest::publish: ds_close failed for %s\n",
        XB_BACKUP_METADATA_JSON);
    return false;
  }
  return true;
}

bool write_to_dir(const char *dir, const std::string &json_text) {
  std::string path = dir;
  path += "/";
  path += XB_BACKUP_METADATA_JSON;
  std::ofstream out(path, std::ios::binary | std::ios::trunc);
  if (!out) {
    msg("xb_manifest::write_to_dir: failed to open %s for writing\n",
        path.c_str());
    return false;
  }
  out.write(json_text.data(), json_text.size());
  if (!out) {
    msg("xb_manifest::write_to_dir: short write to %s\n", path.c_str());
    return false;
  }
  return true;
}

}  // namespace xb_manifest
